# URL
baseurl: /
url: smile4maggie.github.io

# COLLECTIONS
collections:
  gallery:
    output: true
  projects:
    outout: true

# VARIABLES
excerpt_separator: <!--more-->

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num/"

# GEMS
gems:
  - octopress-paginate
